/* Smart Flow BW — deterministic local runtime v4. Web + Android share this file. */
(function(){'use strict';
const DB='smartflow-local-v1',VER=4,ADB='smartflow-accounts-v2';
const S={scenario:'normal',hour:12,playing:false,runId:0};
const $=id=>document.getElementById(id), uid=()=>crypto.randomUUID?crypto.randomUUID():'sf-'+Date.now()+'-'+Math.random().toString(36).slice(2), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const currentUser=()=>{try{return JSON.parse(localStorage.getItem('sf.session')||'null')}catch{return null}};
let dbp;
function openDB(){if(dbp)return dbp;dbp=new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;['devices','readings','alerts','tasks','settings'].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'})})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbp}
async function all(store){const d=await openDB();if(!d.objectStoreNames.contains(store))return[];return new Promise((ok,bad)=>{const q=d.transaction(store,'readonly').objectStore(store).getAll();q.onsuccess=()=>ok(q.result||[]);q.onerror=()=>bad(q.error)})}
async function put(store,obj){const d=await openDB();return new Promise((ok,bad)=>{const q=d.transaction(store,'readwrite').objectStore(store).put(obj);q.onsuccess=()=>ok(obj);q.onerror=()=>bad(q.error)})}
async function del(store,id){const d=await openDB();return new Promise((ok,bad)=>{const q=d.transaction(store,'readwrite').objectStore(store).delete(id);q.onsuccess=ok;q.onerror=()=>bad(q.error)})}
async function accountAll(store){const d=await new Promise((ok,bad)=>{const r=indexedDB.open(ADB,1);r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)});if(!d.objectStoreNames.contains(store))return[];return new Promise((ok,bad)=>{const q=d.transaction(store,'readonly').objectStore(store).getAll();q.onsuccess=()=>ok(q.result||[]);q.onerror=()=>bad(q.error)})}
function toast(text){let x=$('sfToast');if(!x){x=document.createElement('div');x.id='sfToast';x.className='sf-toast';document.body.appendChild(x)}x.textContent=text;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),2400)}
const SC={normal:['Normal household','Normal'],overnight:['Overnight leak','Possible leak'],high:['High flow / burst risk','Burst risk'],improving:['Usage improving','Improving'],spike:['Evening spike','Evening spike']};
function flowAt(h,scenario,selected=S.hour){let v=h>=5&&h<=7?1.15:h>=8&&h<=10?.62:h>=11&&h<=16?.35:h>=17&&h<=21?.92:.08;if(scenario==='overnight'&&(h>=22||h<=5))v+=.55;if(scenario==='high'&&h===selected)v+=5.8;if(scenario==='spike'&&h>=18&&h<=21)v*=3.1;if(scenario==='improving')v*=.62;return Math.max(.03,v)}
function metrics(){const rs=Array.from({length:24},(_,h)=>({hour:h,flow:flowAt(h,S.scenario,S.hour)})),total=rs.reduce((n,x)=>n+x.flow*60,0),current=flowAt(S.hour,S.scenario,S.hour),monthly=total*30,forecast=Math.max(18,monthly*.035);return{rs,total,current,monthly,forecast,saving:Math.max(0,forecast*(S.scenario==='improving'?.18:.1))}}
function emotion(kind){const c=$('thothiChar');if(!c)return;c.className='thothiChar '+kind;const m=$('thothiMouth');if(m)m.textContent={happy:'⌣',thinking:'…',concerned:'︵',excited:'⌣',celebrating:'⌣'}[kind]||'⌣';c.querySelectorAll('.eye').forEach(e=>e.classList.toggle('blink',kind==='thinking'))}
function message(text,who='thothi'){const b=$('chat');if(!b)return;const d=document.createElement('div');d.className='msg '+who;d.textContent=text;b.appendChild(d);b.scrollTop=b.scrollHeight}
const PROMPTS=['What am I looking at?','How much water am I using?','What does Flow Now mean?','What will my bill be?','Why is my forecast changing?','How accurate is the forecast?','Do I have a leak?','What is an overnight leak?','What does Burst Risk mean?','Why did you raise an alert?','How do I acknowledge an alert?','What happens when an alert is resolved?','What does the simulation do?','How do I change the scenario?','Can I run the 24-hour test?','What is a household?','How do I add a household?','How do I add a device?','How do I attach a device to a household?','What is device health?','How do I add a reading?','How can I save water?','How do I add a saving task?','How do I complete or cancel a task?','Am I signed in?','What can an administrator do?'];
function answer(q){const x=q.toLowerCase().trim(),m=metrics();let mood='happy',text;
if(/^(hi|hello|hey|dumela|good morning|good afternoon|good day)[!. ]*$/.test(x))text='Hello! 💧 I’m Thothi. Pick a question below and I’ll guide you — no typing required.';
else if(x.includes('what am i looking'))text='This is your Smart Flow command view: usage, current flow, forecast, alerts, saving actions, households and devices. The simulator feeds the dashboard so the numbers move together.';
else if(x.includes('how much')||x.includes('using'))text=`The ${SC[S.scenario][0].toLowerCase()} scenario represents about ${Math.round(m.total).toLocaleString()} litres across the simulated day.`;
else if(x.includes('flow now'))text=`At ${String(S.hour).padStart(2,'0')}:00, Flow Now is ${m.current.toFixed(2)} L/min in this scenario.`;
else if(x.includes('bill')||x.includes('cost')||x.includes('pula'))text=`The simulated end-of-cycle forecast is about P${m.forecast.toFixed(0)}. This is a Smart Flow demonstration estimate, not an official WUC bill.`;
else if(x.includes('forecast')||x.includes('changing'))text='The forecast is tied to the same 24-hour flow model as Overview. Change the scenario or hour and I recalculate it immediately.';
else if(x.includes('accurate'))text='Right now I am a deterministic demo model. Real meter history, calibrated Botswana tariff rules and live integrations will make future forecasts more precise.';
else if(x.includes('leak')||x.includes('overnight')){mood='concerned';text=S.scenario==='overnight'?'I’m concerned about the night pattern. Continuous overnight flow can indicate a running toilet, dripping tap or hidden leak.':'No overnight-leak signature is active. Select Overnight leak and watch me, the forecast and Alerts react.'}
else if(x.includes('burst')){mood='concerned';text=S.scenario==='high'?'Burst Risk is active because simulated flow is far above normal. Check taps, exposed pipes and the meter area.':'High flow / burst risk demonstrates how Smart Flow reacts to an abnormal spike.'}
else if(x.includes('alert'))text=S.scenario==='normal'?'No simulated anomaly is active. The Alerts page is still live and monitoring the selected state.':'Alerts uses the same scenario, hour and device state as the rest of Smart Flow.';
else if(x.includes('simulation')||x.includes('scenario')||x.includes('24')){mood='excited';text='Choose a scenario, move time with Previous or Next, or start Run 24h. I react as the simulation advances.'}
else if(x.includes('household'))text='A household is a property grouping. You can have multiple households and assign each device to exactly one household.';
else if(x.includes('device')||x.includes('attach'))text='Open Devices, choose Add device, select the household, then open that household to see device health, latest reading, flow, alerts and last-seen time.';
else if(x.includes('reading'))text='A reading belongs to one device. Enter litres and flow, and Smart Flow updates that device without mixing readings from other devices.';
else if(x.includes('save water')||x.includes('saving')){mood='excited';text='Start with leaks, long showers, running taps and unusual night flow. Add a saving action and mark it complete when you finish it.'}
else if(x.includes('task')||x.includes('action'))text='Saving actions can be added, completed, reopened, cancelled/restored and deleted. They are stored per signed-in account on this offline prototype.';
else if(x.includes('signed')||x.includes('account'))text=currentUser()?`You’re signed in as ${currentUser().name} (${currentUser().role}).`:'You’re browsing as a guest. Open Account to sign in, sign up or enter Administrator mode.';
else if(x.includes('administrator')||x.includes('admin'))text='Administrators can oversee accounts, households, devices, tasks and audit activity. Privileged actions are checked before they run.';
else text='I can guide you through usage, forecasts, leaks, alerts, simulations, households, devices, readings, saving actions and accounts. Pick one of the questions below.';return{text,mood}}
function askInternal(t){if(!t)return;message(t,'user');emotion('thinking');setTimeout(()=>{const a=answer(t);message(a.text);emotion(a.mood)},180)}
function modal(title,body){let m=$('sfRuntimeModal');if(!m){m=document.createElement('div');m.id='sfRuntimeModal';m.className='sf-modal';const st=document.createElement('style');st.textContent='.sf-modal{position:fixed;inset:0;background:#001827aa;z-index:999;display:none;align-items:flex-end;justify-content:center;padding:10px}.sf-modal.open{display:flex}.sf-box{width:min(760px,100%);max-height:94vh;overflow:auto;background:#fff;border-radius:22px;padding:18px;box-shadow:0 30px 80px #0005}.sf-form{display:grid;gap:9px}.sf-form label{font-size:11px;font-weight:800;color:var(--muted)}.sf-form input,.sf-form select{padding:11px;border:1px solid var(--line);border-radius:10px}';document.head.appendChild(st);document.body.appendChild(m)}m.innerHTML=`<div class="sf-box"><div class="row"><h2 style="margin:0">${title}</h2><button class="btn soft" type="button" onclick="sfCloseRuntimeModal()">×</button></div><div style="margin-top:12px">${body}</div></div>`;m.classList.add('open')}
window.sfCloseRuntimeModal=()=>$("sfRuntimeModal")?.classList.remove('open');
function taskRows(list){return list.map(t=>`<div class="task"><input type="checkbox" ${t.done?'checked':''} ${t.cancelled?'disabled':''} onchange="sfTaskToggle('${t.id}',this.checked)"><span class="tasktext ${t.done?'done':''}">${esc(t.text)}${t.cancelled?' · Cancelled':''}</span><button class="iconbtn" onclick="sfTaskCancel('${t.id}')">${t.cancelled?'Restore':'Cancel'}</button><button class="iconbtn danger" onclick="sfTaskDelete('${t.id}')">Delete</button></div>`).join('')}
async function renderTasks(){const b=$('tasks');if(!b)return;const u=currentUser();const list=u?(await all('tasks')).filter(t=>t.ownerId===u.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)):[];b.innerHTML=list.length?taskRows(list):'<div class="empty">No saving actions yet. Add your first action below.</div>'}
window.addTask=async()=>{const u=currentUser();if(!u){toast('Sign in to manage saving actions');window.sfOpenAccount?.();return}modal('Add water-saving action',`<form class="sf-form" onsubmit="event.preventDefault();sfCreateTask(this)"><label>Action</label><input name="text" placeholder="Fix a dripping tap" required maxlength="120"><label>Optional note</label><input name="note" placeholder="e.g. Kitchen sink"><button class="btn dark">Add action</button></form>`) };
window.sfCreateTask=async f=>{const u=currentUser();if(!u)return;const text=f.text.value.trim();if(!text)return;await put('tasks',{id:uid(),ownerId:u.id,text,note:f.note.value.trim(),done:false,cancelled:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});sfCloseRuntimeModal();await renderTasks();emotion('celebrating');toast('Saving action added')};
window.sfTaskToggle=async(id,v)=>{const t=(await all('tasks')).find(x=>x.id===id);if(!t)return;t.done=!!v;t.cancelled=false;t.updatedAt=new Date().toISOString();await put('tasks',t);await renderTasks();emotion(v?'celebrating':'happy');toast(v?'Task completed':'Task reopened')};
window.sfTaskCancel=async id=>{const t=(await all('tasks')).find(x=>x.id===id);if(!t)return;t.cancelled=!t.cancelled;t.done=false;t.updatedAt=new Date().toISOString();await put('tasks',t);await renderTasks();toast(t.cancelled?'Task cancelled':'Task restored')};
window.sfTaskDelete=async id=>{await del('tasks',id);await renderTasks();toast('Task deleted')};
async function accountHouseholds(){const u=currentUser();return u?(await accountAll('households')).filter(h=>h.ownerId===u.id):[]}
async function coreDevices(){return(await all('devices')).filter(d=>{const u=currentUser();return u&&d.ownerId===u.id})}
function deviceCard(d,rs,alerts){const latest=rs.filter(r=>r.deviceId===d.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0],open=alerts.filter(a=>a.deviceId===d.id&&!a.resolved),health=d.status==='offline'?'Offline':open.some(a=>a.severity==='critical')?'Attention':'Healthy';return `<div class="device"><div class="deviceTop"><div><b>📡 ${esc(d.name)}</b><small>${esc(d.type||'Water meter')} · ${esc(d.location||'Household')}</small></div><span class="health ${health.toLowerCase()}">${health}</span></div><div class="deviceGrid"><div><small>Latest flow</small><strong>${latest?Number(latest.flow).toFixed(2):'0.00'} L/min</strong></div><div><small>Latest reading</small><strong>${latest?Number(latest.litres).toFixed(1):'—'} L</strong></div><div><small>Active alerts</small><strong>${open.length}</strong></div></div><div class="deviceActions"><button class="iconbtn" onclick="sfRecordReading('${d.id}')">＋ Reading</button><button class="iconbtn" onclick="sfDeviceDetail('${d.id}')">Monitor</button><button class="iconbtn" onclick="sfMoveDevice('${d.id}')">Move</button><button class="iconbtn danger" onclick="sfDeleteDevice('${d.id}')">Delete</button></div></div>`}
async function renderDevicePanel(){const b=$('sfDevicePanel');if(!b)return;const u=currentUser();if(!u){b.innerHTML='<div class="empty">Sign in to manage households and devices.</div><button class="btn dark" onclick="sfOpenAccount()">🔐 Sign in / Sign up</button>';return}const hs=await accountHouseholds(),ds=await coreDevices(),rs=await all('readings'),as=await all('alerts');let html='<div class="device-actions"><button class="btn dark" onclick="sfAddHouseholdDevice()">＋ Add device</button><button class="btn soft" onclick="sfHouseholdsManager()">🏠 Manage households</button></div>';if(!hs.length)html+='<div class="notice">Create a household first. Every device must belong to one household.</div>';for(const h of hs){const hd=ds.filter(d=>d.householdId===h.id);html+=`<div class="house"><div class="househead"><button class="iconbtn" onclick="sfHouseholdDetail('${h.id}')">🏠 ${esc(h.name)}</button><span>${hd.length} device${hd.length===1?'':'s'}</span></div><small>${esc(h.address||'Address not set')}</small>${hd.length?hd.map(d=>deviceCard(d,rs,as)).join(''):'<div class="empty">No devices in this household yet.</div>'}</div>`}b.innerHTML=html}
window.sfAddHouseholdDevice=async()=>{const u=currentUser();if(!u)return window.sfOpenAccount?.();const hs=await accountHouseholds();if(!hs.length)return window.sfCreateHouseholdUI?.();modal('Add device',`<form class="sf-form" onsubmit="event.preventDefault();sfCreateDevice(this)"><label>Household</label><select name="household" required>${hs.map(h=>`<option value="${h.id}">${esc(h.name)}</option>`).join('')}</select><label>Device name</label><input name="name" value="Main water meter" required maxlength="80"><label>Device type</label><select name="type"><option>Household water meter</option><option>Smart flow meter</option><option>Tank level meter</option><option>Other</option></select><label>Location</label><input name="location" placeholder="Main meter / kitchen / yard"><button class="btn dark">Add device</button></form>`)};
window.sfCreateDevice=async f=>{const u=currentUser();if(!u)return;const name=f.name.value.trim();if(!name)return;const t=new Date().toISOString();await put('devices',{id:uid(),ownerId:u.id,householdId:f.household.value,name,type:f.type.value,location:f.location.value.trim(),serial:'SF-'+Math.random().toString(36).slice(2,9).toUpperCase(),status:'online',createdAt:t,lastSeen:t});sfCloseRuntimeModal();await renderDevicePanel();toast('Device added to household');emotion('celebrating')};
window.sfRecordReading=async id=>{const u=currentUser(),d=(await all('devices')).find(x=>x.id===id);if(!u||!d||d.ownerId!==u.id)return toast('You do not have access to this device');modal('Add test reading',`<form class="sf-form" onsubmit="event.preventDefault();sfSaveReading(this,'${id}')"><div class="notice">Simulator data is labelled as test/demo data and stays attached to this device.</div><label>Litres</label><input name="litres" type="number" min="0" step="0.1" value="50" required><label>Flow rate (L/min)</label><input name="flow" type="number" min="0" step="0.01" value="0.8" required><button class="btn dark">Save reading</button></form>`)};
window.sfSaveReading=async(f,id)=>{const u=currentUser(),d=(await all('devices')).find(x=>x.id===id);const litres=Number(f.litres.value),flow=Number(f.flow.value);if(!u||!d||d.ownerId!==u.id||!Number.isFinite(litres)||!Number.isFinite(flow)||litres<0||flow<0)return toast('Enter valid reading values');const t=new Date().toISOString();await put('readings',{id:uid(),deviceId:id,ownerId:u.id,litres,flow,createdAt:t,source:'manual/demo'});d.lastSeen=t;d.status='online';await put('devices',d);if(flow>5)await put('alerts',{id:uid(),deviceId:id,ownerId:u.id,title:'High flow detected',severity:'critical',message:`${d.name} is flowing at ${flow.toFixed(1)} L/min.`,resolved:false,createdAt:t});else if(flow>.3){const h=new Date().getHours();if(h>=22||h<6)await put('alerts',{id:uid(),deviceId:id,ownerId:u.id,title:'Possible overnight leak',severity:'warning',message:`${d.name} has continuous night flow of ${flow.toFixed(1)} L/min.`,resolved:false,createdAt:t})}sfCloseRuntimeModal();await renderDevicePanel();await renderAlerts();toast('Reading recorded');emotion(flow>5?'concerned':'happy')};
window.sfMoveDevice=async id=>{const u=currentUser(),d=(await all('devices')).find(x=>x.id===id),hs=await accountHouseholds();if(!u||!d||d.ownerId!==u.id)return;modal('Move device',`<form class="sf-form" onsubmit="event.preventDefault();sfDoMove(this,'${id}')"><label>New household</label><select name="household">${hs.map(h=>`<option value="${h.id}" ${h.id===d.householdId?'selected':''}>${esc(h.name)}</option>`).join('')}</select><button class="btn dark">Move device</button></form>`)};
window.sfDoMove=async(f,id)=>{const d=(await all('devices')).find(x=>x.id===id),u=currentUser();if(!u||!d||d.ownerId!==u.id)return;d.householdId=f.household.value;await put('devices',d);sfCloseRuntimeModal();await renderDevicePanel();toast('Device moved')};
window.sfDeleteDevice=async id=>{const u=currentUser(),d=(await all('devices')).find(x=>x.id===id);if(!u||!d||d.ownerId!==u.id)return;if(!confirm(`Delete ${d.name} and its readings/alerts?`))return;await del('devices',id);for(const r of await all('readings'))if(r.deviceId===id)await del('readings',r.id);for(const a of await all('alerts'))if(a.deviceId===id)await del('alerts',a.id);await renderDevicePanel();await renderAlerts();toast('Device deleted')};
window.sfDeviceDetail=async id=>{const u=currentUser(),d=(await all('devices')).find(x=>x.id===id);if(!u||!d||d.ownerId!==u.id)return;const rs=(await all('readings')).filter(x=>x.deviceId===id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,20),as=(await all('alerts')).filter(x=>x.deviceId===id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));modal(`📡 ${esc(d.name)}`,`<div class="deviceGrid"><div><small>Health</small><strong>${d.status==='offline'?'Offline':'Healthy'}</strong></div><div><small>Latest flow</small><strong>${rs[0]?Number(rs[0].flow).toFixed(2):'0.00'} L/min</strong></div><div><small>Readings</small><strong>${rs.length}</strong></div></div><p class="sf-small">${esc(d.location||'Location not set')} · Last seen ${d.lastSeen?new Date(d.lastSeen).toLocaleString():'never'}</p><h3>Recent readings</h3>${rs.length?rs.map(r=>`<div class="sf-small">${new Date(r.createdAt).toLocaleString()} · ${Number(r.litres).toFixed(1)} L · ${Number(r.flow).toFixed(2)} L/min · ${esc(r.source||'demo')}</div>`).join(''):'<div class="empty">No readings yet.</div>'}<h3>Alerts for this device</h3>${as.length?as.map(a=>`<div class="sf-small">${a.resolved?'✓ Resolved':'⚠ Active'} · ${esc(a.title)} · ${new Date(a.createdAt).toLocaleString()}</div>`).join(''):'<div class="empty">No device alerts.</div>'}`)};
window.sfHouseholdDetail=async id=>{const u=currentUser(),hs=await accountHouseholds(),h=hs.find(x=>x.id===id);if(!u||!h)return;const ds=(await coreDevices()).filter(d=>d.householdId===id),rs=await all('readings'),as=await all('alerts');modal(`🏠 ${esc(h.name)}`,`<p class="sf-small">${esc(h.address||'Address not set')}</p><div class="deviceGrid"><div><small>Devices</small><strong>${ds.length}</strong></div><div><small>Latest litres</small><strong>${ds.reduce((n,d)=>{const r=rs.filter(x=>x.deviceId===d.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];return n+(r?Number(r.litres):0)},0).toFixed(1)} L</strong></div><div><small>Open alerts</small><strong>${as.filter(a=>ds.some(d=>d.id===a.deviceId)&&!a.resolved).length}</strong></div></div>${ds.length?ds.map(d=>deviceCard(d,rs,as)).join(''):'<div class="empty">This household has no devices yet.</div>'}`)};
window.sfHouseholdsManager=async()=>{const hs=await accountHouseholds();modal('My households',`<div class="device-actions"><button class="btn dark" onclick="sfCreateHouseholdUI()">＋ Add household</button></div>${hs.length?hs.map(h=>`<div class="house"><div class="househead"><button class="iconbtn" onclick="sfHouseholdDetail('${h.id}')">🏠 ${esc(h.name)}</button><span>Open details →</span></div><small>${esc(h.address||'Address not set')}</small></div>`).join(''):'<div class="empty">No households yet. Create your first one.</div>'}`)};
window.sfCreateHouseholdUI=()=>modal('Add household',`<form class="sf-form" onsubmit="event.preventDefault();sfCreateHousehold(this)"><label>Household name</label><input name="name" placeholder="My Home" required maxlength="80"><label>Address / area</label><input name="address" placeholder="Gaborone / Block ..."><button class="btn dark">Create household</button></form>`);
window.sfCreateHousehold=async f=>{const u=currentUser();if(!u)return;const name=f.name.value.trim();if(!name)return;const d=await new Promise((ok,bad)=>{const r=indexedDB.open(ADB,1);r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)});const obj={id:uid(),ownerId:u.id,name,address:f.address.value.trim(),createdAt:new Date().toISOString()};await new Promise((ok,bad)=>{const q=d.transaction('households','readwrite').objectStore('households').put(obj);q.onsuccess=ok;q.onerror=()=>bad(q.error)});sfCloseRuntimeModal();await renderDevicePanel();toast('Household created');emotion('celebrating')};
async function seedStarterTasks(){const u=currentUser();if(!u)return;const list=(await all('tasks')).filter(t=>t.ownerId===u.id);if(list.length)return;for(const text of ['Check taps for drips','Check the toilet for continuous running','Avoid leaving taps running while brushing teeth'])await put('tasks',{id:uid(),ownerId:u.id,text,done:false,cancelled:false,starter:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})}
async function renderAlerts(){const b=$('alertsList');if(!b)return;const m=metrics(),live=[];if(S.scenario==='overnight')live.push({severity:'warning',title:'Possible overnight leak',message:'Continuous night flow is above the normal idle pattern.'});if(S.scenario==='high'&&m.current>5)live.push({severity:'critical',title:'High flow / burst risk',message:`Current simulated flow is ${m.current.toFixed(1)} L/min.`});if(S.scenario==='spike'&&S.hour>=18&&S.hour<=21)live.push({severity:'warning',title:'Evening usage spike',message:'The selected hour is inside a simulated evening peak.'});if(S.scenario==='normal')live.push({severity:'healthy',title:'All clear',message:'No simulated anomaly is active. Thothi is still monitoring.'});const u=currentUser();if(u)for(const a of (await all('alerts')).filter(x=>x.ownerId===u.id&&!x.resolved).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,8))live.push(a);b.innerHTML=live.map((a,i)=>a.severity==='healthy'?`<div class="healthy"><div class="pulse">✓</div><b>${a.title}</b><p>${a.message}</p><small>Live Smart Flow state · ${String(S.hour).padStart(2,'0')}:00</small></div>`:`<div class="alert ${a.severity==='critical'?'critical':''}"><div><b>${esc(a.title)}</b><small>${a.deviceId?'Device alert':'Live simulation'} · ${String(S.hour).padStart(2,'0')}:00</small><p>${esc(a.message||a.description||'Monitoring event')}</p></div><button class="btn soft" onclick="sfAcknowledgeAlert(${a.id?`'${a.id}'`:'null'},${i})">${a.id?'Resolve':'Acknowledge'}</button></div>`).join('')}
window.sfAcknowledgeAlert=async(id)=>{if(id){const a=(await all('alerts')).find(x=>x.id===id);if(a){a.resolved=true;a.resolvedAt=new Date().toISOString();await put('alerts',a)}}await renderAlerts();await renderDevicePanel();emotion('happy');toast('Alert acknowledged')};
function renderChart(m){const c=$('chart');if(!c)return;const mx=Math.max(...m.rs.map(x=>x.flow),.01);c.innerHTML=m.rs.map(x=>`<div class="barc ${x.hour===S.hour?'selected':''}" title="${String(x.hour).padStart(2,'0')}:00 · ${x.flow.toFixed(2)} L/min" style="height:${Math.max(6,x.flow/mx*100)}%"></div>`).join('')}
function renderAll(){const m=metrics();if($('scenario'))$('scenario').value=S.scenario;if($('hour'))$('hour').value=S.hour;if($('timeLabel'))$('timeLabel').textContent=String(S.hour).padStart(2,'0')+':00';if($('scenarioBadge'))$('scenarioBadge').textContent=SC[S.scenario][1];if($('mToday'))$('mToday').textContent=Math.round(m.total)+' L';if($('mBill'))$('mBill').textContent='P'+m.forecast.toFixed(0);if($('mFlow'))$('mFlow').textContent=m.current.toFixed(2)+' L/min';if($('mSave'))$('mSave').textContent='P'+m.saving.toFixed(0);if($('billCurrent'))$('billCurrent').textContent='P'+(m.forecast*.47).toFixed(0);if($('billForecast'))$('billForecast').textContent='P'+m.forecast.toFixed(0);if($('billUsed'))$('billUsed').textContent=Math.round(m.total*.47)+' L used';if($('billExplain'))$('billExplain').textContent=`${SC[S.scenario][0]}: forecast is calculated from the same simulated flow shown on Overview at ${String(S.hour).padStart(2,'0')}:00.`;if($('cyclePct'))$('cyclePct').textContent='47%';if($('cycleFill'))$('cycleFill').style.width='47%';if($('insightTitle'))$('insightTitle').textContent=S.scenario==='normal'?'Thothi is watching. 👀':'Thothi spotted a pattern. 💧';if($('insightText'))$('insightText').textContent=S.scenario==='overnight'?'Night flow is elevated. Check toilets, taps and hidden leaks.':S.scenario==='high'?'Flow is unusually high. Check for burst-pipe risk.':S.scenario==='improving'?'Your simulated usage is trending lower. Keep it going!':'Everything is calm in this simulation.';renderChart(m);renderTasks();renderDevicePanel();renderAlerts()}
window.advanceHour=d=>{if(S.playing)return;S.hour=(S.hour+d+24)%24;renderAll();emotion(S.scenario==='normal'?'happy':S.scenario==='improving'?'excited':'concerned');toast(`Simulation time ${String(S.hour).padStart(2,'0')}:00`)};
window.runScenario=()=>{if(S.playing)return;S.playing=true;S.runId++;const id=S.runId;let h=0;emotion('excited');toast('Running 24-hour intelligence test…');const timer=setInterval(()=>{if(id!==S.runId){clearInterval(timer);return}S.hour=h;renderAll();h++;if(h>23){clearInterval(timer);S.playing=false;S.hour=23;renderAll();emotion('celebrating');toast('24-hour test complete');message('24-hour simulation complete. Overview, forecast, alerts and I followed the same timeline. 💧')}},180)};
window.stopScenario=()=>{S.runId++;S.playing=false;renderAll();emotion('happy');toast('Simulation stopped')};
function wire(){const sel=$('scenario');if(sel)sel.onchange=()=>{S.scenario=sel.value;renderAll();emotion(S.scenario==='normal'?'happy':S.scenario==='improving'?'excited':'concerned');message(`I switched to ${SC[S.scenario][0]}. Watch the dashboard and Alerts change with me.`)};const hour=$('hour');if(hour)hour.oninput=()=>{if(!S.playing){S.hour=Number(hour.value);renderAll()}};document.querySelectorAll('[data-action="prev"]').forEach(b=>b.onclick=()=>advanceHour(-1));document.querySelectorAll('[data-action="next"]').forEach(b=>b.onclick=()=>advanceHour(1));document.querySelectorAll('[data-action="run"]').forEach(b=>b.onclick=runScenario);const sug=$('suggestions');if(sug){sug.innerHTML=PROMPTS.map(p=>`<button class="prompt" type="button" data-prompt="${esc(p)}">${esc(p)}</button>`).join('');sug.querySelectorAll('.prompt').forEach(b=>b.onclick=()=>sfAsk(b.dataset.prompt||''));}window.sfAsk=p=>{const i=$('chatInput');if(i)i.value=p;askInternal(p)};window.askThothi=()=>{const i=$('chatInput'),q=(i?.value||'').trim();if(i)i.value='';askInternal(q)};$('chatInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')window.askThothi()});if($('chat')&&!$('chat').children.length)message('Hi! I’m Thothi 💧 Choose a question below — you do not have to type first.');window.addEventListener('sf-auth-changed',async()=>{await seedStarterTasks();renderAll()});renderAll();emotion('happy');window.__smartFlowRuntimeReady=true}
function injectCSS(){if($('sf-runtime-css'))return;const s=document.createElement('style');s.id='sf-runtime-css';s.textContent='.sf-modal{position:fixed;inset:0;background:#001827aa;z-index:3000;display:none;align-items:flex-end;justify-content:center;padding:10px}.sf-modal.open{display:flex}.sf-box{width:min(760px,100%);max-height:94vh;overflow:auto;background:#fff;border-radius:22px;padding:18px;box-shadow:0 30px 80px #0005}.sf-form{display:grid;gap:9px}.sf-form label{font-size:11px;font-weight:800;color:var(--muted)}.sf-form input,.sf-form select{padding:11px;border:1px solid var(--line);border-radius:10px;background:#fff}.sf-small{font-size:11px;color:var(--muted);padding:7px 0;border-bottom:1px solid var(--line)}.row{display:flex;justify-content:space-between;gap:10px;align-items:center}.barc.selected{outline:2px solid #08243d;outline-offset:2px}.eye.blink{animation:sfblink .8s infinite}@keyframes sfblink{0%,92%,100%{transform:scaleY(1)}96%{transform:scaleY(.15)}}.splashEye{position:absolute;top:54px;width:15px;height:20px;border-radius:50%;background:#08243d;z-index:2}.splashEye.l{left:31px}.splashEye.r{right:31px}.splashMouth{position:absolute;top:78px;left:35px;width:35px;text-align:center;color:#08243d;font-weight:900;font-size:25px;z-index:2}';document.head.appendChild(s)}
function addSplashFace(){const d=$('splash')?.querySelector('.splashDrop');if(d&&!d.querySelector('.splashEye')){d.insertAdjacentHTML('beforeend','<div class="splashEye l"></div><div class="splashEye r"></div><div class="splashMouth">⌣</div>')}}
function boot(){injectCSS();addSplashFace();setTimeout(()=>{try{wire();seedStarterTasks().then(renderAll)}catch(e){console.error(e);toast('Smart Flow recovered from a runtime error.')}const splash=$('splash');setTimeout(()=>splash?.classList.add('hide'),1700)},60);let last=JSON.stringify(currentUser());setInterval(()=>{const now=JSON.stringify(currentUser());if(now!==last){last=now;window.dispatchEvent(new Event('sf-auth-changed'))}},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
