/* Smart Flow BW — unified, deterministic offline runtime v3. */
(function(){'use strict';
const DB='smartflow-local-v1', VER=3;
const S={scenario:'normal',hour:12,playing:false};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():'sf-'+Date.now()+'-'+Math.random().toString(36).slice(2);
const currentUser=()=>{try{return JSON.parse(localStorage.getItem('sf.session')||'null')}catch{return null}};
let dbp;
function openDB(){if(dbp)return dbp;dbp=new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;['devices','readings','alerts','tasks','settings'].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'})})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbp}
async function all(store){try{const d=await openDB();if(!d.objectStoreNames.contains(store))return [];return await new Promise((ok,bad)=>{const q=d.transaction(store,'readonly').objectStore(store).getAll();q.onsuccess=()=>ok(q.result||[]);q.onerror=()=>bad(q.error)})}catch(e){console.warn('Smart Flow store read failed',store,e);return []}}
async function put(store,obj){const d=await openDB();return new Promise((ok,bad)=>{const q=d.transaction(store,'readwrite').objectStore(store).put(obj);q.onsuccess=()=>ok(obj);q.onerror=()=>bad(q.error)})}
async function del(store,id){const d=await openDB();return new Promise((ok,bad)=>{const q=d.transaction(store,'readwrite').objectStore(store).delete(id);q.onsuccess=()=>ok();q.onerror=()=>bad(q.error)})}
async function accounts(store){try{const r=indexedDB.open('smartflow-accounts-v2',1);return await new Promise((ok,bad)=>{r.onsuccess=()=>{const d=r.result;if(!d.objectStoreNames.contains(store))return ok([]);const q=d.transaction(store,'readonly').objectStore(store).getAll();q.onsuccess=()=>ok(q.result||[]);q.onerror=()=>bad(q.error)};r.onerror=()=>bad(r.error)})}catch{return []}}
function toast(text){let x=$('sfToast');if(!x){x=document.createElement('div');x.id='sfToast';x.className='sf-toast';document.body.appendChild(x)}x.textContent=text;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),2400)}
const SC={normal:['Normal household','Normal'],overnight:['Overnight leak','Possible leak'],high:['High flow / burst risk','Burst risk'],improving:['Usage improving','Improving'],spike:['Evening spike','Evening spike']};
function flowAt(hour,scenario,selected=S.hour){let v=hour>=5&&hour<=7?1.15:hour>=8&&hour<=10?.62:hour>=11&&hour<=16?.35:hour>=17&&hour<=21?.92:.08;if(scenario==='overnight'&&(hour>=22||hour<=5))v+=.55;if(scenario==='high'&&hour===selected)v+=5.8;if(scenario==='spike'&&hour>=18&&hour<=21)v*=3.1;if(scenario==='improving')v*=.62;return Math.max(.03,v)}
function metrics(){const rs=Array.from({length:24},(_,h)=>({hour:h,flow:flowAt(h,S.scenario,S.hour)}));const total=rs.reduce((a,x)=>a+x.flow*60,0);const current=flowAt(S.hour,S.scenario,S.hour);const forecast=Math.max(18,total*30*.035);return{rs,total,current,forecast,saving:Math.max(0,forecast*(S.scenario==='improving'?.18:.1))}}
function emotion(kind){const c=$('thothiChar');if(!c)return;c.className='thothiChar '+kind;const m=$('thothiMouth');if(m)m.textContent={happy:'⌣',thinking:'…',concerned:'︵',excited:'⌣',celebrating:'⌣'}[kind]||'⌣'}
function message(text,who='thothi'){const b=$('chat');if(!b)return;const d=document.createElement('div');d.className='msg '+who;d.textContent=text;b.appendChild(d);b.scrollTop=b.scrollHeight}
const PROMPTS=['What am I looking at?','How much water am I using?','What does Flow Now mean?','What will my bill be?','Why is my forecast changing?','How accurate is the forecast?','Do I have a leak?','What is an overnight leak?','What does Burst Risk mean?','Why did you raise an alert?','How do I acknowledge an alert?','What happens when an alert is resolved?','What does the simulation do?','How do I change the scenario?','Can I run the 24-hour test?','What is a household?','How do I add a household?','How do I add a device?','How do I attach a device to a household?','What is device health?','How do I add a reading?','How can I save water?','How do I add a saving task?','How do I complete or cancel a task?','Am I signed in?','What can an administrator do?'];
function answer(question){const x=question.toLowerCase().trim(),m=metrics();let mood='happy',text;
if(/^(hi|hello|hey|dumela|good morning|good afternoon|good day)[!. ]*$/.test(x))text='Hello! 💧 I’m Thothi. You do not need to type first — choose one of my questions below and I’ll guide you.';
else if(x.includes('what am i looking'))text='This is your Smart Flow command view: water usage, current flow, bill forecast, alerts, saving actions, households and devices. Everything is linked to the same simulation state.';
else if(x.includes('how much')||x.includes('using'))text=`The ${SC[S.scenario][0].toLowerCase()} simulation represents about ${Math.round(m.total)} litres across the simulated day.`;
else if(x.includes('flow now'))text=`At ${String(S.hour).padStart(2,'0')}:00, Flow Now is ${m.current.toFixed(2)} L/min in the simulation.`;
else if(x.includes('bill')||x.includes('cost')||x.includes('pula'))text=`The current simulated end-of-cycle forecast is about P${m.forecast.toFixed(0)}. It is an estimate for demonstration, not an official WUC bill.`;
else if(x.includes('forecast')||x.includes('changing'))text='The forecast is driven by the same simulated flow data as Overview. Change the scenario or time and I recalculate it immediately.';
else if(x.includes('accurate'))text='At this stage I am a deterministic demo model. Real meter history, calibrated tariff rules and live integrations will improve forecast accuracy later.';
else if(x.includes('leak')||x.includes('overnight')){mood='concerned';text=S.scenario==='overnight'?'I’m concerned about the night pattern. Continuous overnight flow can point to a running toilet, dripping tap or hidden leak.':'No overnight-leak signature is active. Switch the scenario to Overnight leak and watch Alerts and me react.'}
else if(x.includes('burst')){mood='concerned';text=S.scenario==='high'?'Burst Risk is active because the simulated flow is far above normal. Check exposed pipes, taps and the meter area.':'High flow / burst risk shows how I react when an abnormal flow spike occurs.'}
else if(x.includes('alert'))text=S.scenario==='normal'?'No simulated anomaly is active. Alerts still shows a live monitoring state.':'Alerts uses the same scenario, hour and device state as the rest of Smart Flow, so it changes with the app.';
else if(x.includes('simulation')||x.includes('scenario')||x.includes('24')){mood='excited';text='Choose a scenario, move the hour with Previous or Next, or start the 24-hour playback. I react as the simulation runs.'}
else if(x.includes('household'))text='A household is a property grouping. You can create multiple households and assign each water device to exactly the household it belongs to.';
else if(x.includes('device')||x.includes('attach'))text='Open Devices, add a device, choose its household, then open that household to see its device health, latest reading, flow and alerts. Devices can also be moved between your households.';
else if(x.includes('reading'))text='A reading is a measurement recorded against one device. Add litres and flow, then the device health and alert state update from that reading.';
else if(x.includes('save water')||x.includes('saving')){mood='excited';text='Start with leaks, long showers, running taps and unusual night flow. Add a saving action and mark it complete when you finish it.'}
else if(x.includes('task')||x.includes('action'))text='Saving actions can be added, completed, reopened, cancelled/restored and deleted. They persist for the signed-in account.';
else if(x.includes('signed')||x.includes('account'))text=currentUser()?`You’re signed in as ${currentUser().name} (${currentUser().role}).`:'You’re browsing as a guest. Use Account to sign in, sign up or enter the administrator area.';
else if(x.includes('administrator')||x.includes('admin'))text='Administrators can oversee accounts, roles, households, devices and audit activity. Privileged actions are checked before they run.';
else text='I can guide you through usage, forecasts, leaks, alerts, simulations, households, devices, readings, saving actions and accounts. Pick a question below.';return{text,mood}}
function askThothiInternal(t){if(!t)return;message(t,'user');emotion('thinking');setTimeout(()=>{const a=answer(t);message(a.text);emotion(a.mood)},260)}
async function renderTasks(){const b=$('tasks');if(!b)return;const u=currentUser();const list=(await all('tasks')).filter(t=>u&&t.ownerId===u.id);b.innerHTML=list.length?list.map(t=>`<div class="task"><input type="checkbox" ${t.done?'checked':''} onchange="sfTaskToggle('${t.id}',this.checked)"><span class="tasktext ${t.done?'done':''}">${esc(t.text)}${t.cancelled?' · Cancelled':''}</span><button class="iconbtn" onclick="sfTaskCancel('${t.id}')">${t.cancelled?'Restore':'Cancel'}</button><button class="iconbtn danger" onclick="sfTaskDelete('${t.id}')">Delete</button></div>`).join(''):'<div class="empty">No saving actions yet. Add one below.</div>'}
window.addTask=async()=>{const u=currentUser();if(!u){toast('Sign in to save actions');window.sfOpenAccount?.();return}const text=prompt('What water-saving action should we add?');if(!text?.trim())return;await put('tasks',{id:uid(),ownerId:u.id,text:text.trim(),done:false,cancelled:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});await renderTasks();emotion('celebrating');toast('Saving action added')};
window.sfTaskToggle=async(id,v)=>{const t=(await all('tasks')).find(x=>x.id===id);if(!t)return;t.done=!!v;t.cancelled=false;t.updatedAt=new Date().toISOString();await put('tasks',t);await renderTasks();toast(v?'Task completed':'Task reopened')};
window.sfTaskCancel=async id=>{const t=(await all('tasks')).find(x=>x.id===id);if(!t)return;t.cancelled=!t.cancelled;t.updatedAt=new Date().toISOString();await put('tasks',t);await renderTasks();toast(t.cancelled?'Task cancelled':'Task restored')};
window.sfTaskDelete=async id=>{await del('tasks',id);await renderTasks();toast('Task deleted')};
async function renderDevicePanel(){const b=$('devicePanel');if(!b)return;const u=currentUser();if(!u){b.innerHTML='<div class="empty">Sign in to manage households and devices.</div><button class="btn dark" onclick="sfOpenAccount()">🔐 Sign in / Sign up</button>';return}const hs=(await accounts('households')).filter(h=>h.ownerId===u.id),ds=(await all('devices')).filter(d=>d.ownerId===u.id),rs=await all('readings'),alerts=await all('alerts');let html='<div class="device-actions"><button class="btn dark" onclick="sfAddHouseholdDevice()">+ Add device</button><button class="btn soft" onclick="sfHouseholdsManager()">🏠 Manage households</button></div>';if(!hs.length)html+='<div class="notice">Every device belongs to a household. Create a household first.</div>';for(const h of hs){const hd=ds.filter(d=>d.householdId===h.id);html+=`<div class="house"><div class="househead"><button class="iconbtn" onclick="sfHouseholdDetail('${h.id}')">🏠 ${esc(h.name)}</button><span>${hd.length} device${hd.length===1?'':'s'}</span></div><small>${esc(h.address||'Address not set')}</small>${hd.length?hd.map(d=>deviceCard(d,rs,alerts)).join(''):'<div class="empty">No devices in this household yet.</div>'}</div>`}b.innerHTML=html}
function deviceCard(d,rs,alerts){const latest=rs.filter(r=>r.deviceId===d.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0],open=alerts.filter(a=>a.deviceId===d.id&&!a.resolved),health=d.status==='offline'?'Offline':open.some(a=>a.severity==='critical')?'Attention':'Healthy';return `<div class="device"><div class="deviceTop"><div><b>📡 ${esc(d.name)}</b><small>${esc(d.type||'Water meter')} · ${esc(d.serial||'No serial')}</small></div><span class="health ${health.toLowerCase()}">${health}</span></div><div class="deviceGrid"><div><small>Latest flow</small><strong>${latest?Number(latest.flow).toFixed(2):'0.00'} L/min</strong></div><div><small>Latest reading</small><strong>${latest?Number(latest.litres).toFixed(1):'—'} L</strong></div><div><small>Active alerts</small><strong>${open.length}</strong></div></div><div class="deviceActions"><button class="iconbtn" onclick="sfRecordReading('${d.id}')">＋ Reading</button><button class="iconbtn" onclick="sfDeviceDetail('${d.id}')">Monitor</button><button class="iconbtn" onclick="sfMoveDevice('${d.id}')">Move</button><button class="iconbtn danger" onclick="sfDeleteDevice('${d.id}')">Delete</button></div></div>`}
window.sfAddHouseholdDevice=async()=>{const u=currentUser();if(!u)return window.sfOpenAccount?.();const hs=(await accounts('households')).filter(h=>h.ownerId===u.id);if(!hs.length){toast('Create a household first');return window.sfHouseholdsManager?.()}const options=hs.map((h,i)=>`${i+1}. ${h.name}`).join('\n');const n=Number(prompt(`Choose household:\n${options}\n\nEnter number:`));const h=hs[n-1];if(!h)return;const name=prompt('Device name','Main water meter');if(!name?.trim())return;const type=prompt('Device type','Household water meter')||'Household water meter';await put('devices',{id:uid(),ownerId:u.id,householdId:h.id,name:name.trim(),type,serial:'SF-'+Math.random().toString(36).slice(2,10).toUpperCase(),status:'online',createdAt:new Date().toISOString(),lastSeen:new Date().toISOString()});await renderDevicePanel();toast(`Device added to ${h.name}`);emotion('celebrating')};
window.sfRecordReading=async id=>{const u=currentUser(),d=(await all('devices')).find(x=>x.id===id);if(!u||!d||(u.role!=='admin'&&d.ownerId!==u.id))return;const litres=Number(prompt('Reading / litres used','50')),flowRate=Number(prompt('Flow rate (L/min)','0.8'));if(!Number.isFinite(litres)||!Number.isFinite(flowRate)||litres<0||flowRate<0)return;const t=new Date().toISOString();await put('readings',{id:uid(),deviceId:id,ownerId:d.ownerId,litres,flow:flowRate,createdAt:t,source:'manual/demo'});d.lastSeen=t;d.status='online';await put('devices',d);if(flowRate>5)await put('alerts',{id:uid(),deviceId:id,ownerId:d.ownerId,title:'High flow detected',severity:'critical',message:`${d.name} is flowing at ${flowRate.toFixed(1)} L/min.`,resolved:false,createdAt:t});else if(flowRate>.3){const h=new Date().getHours();if(h>=22||h<6)await put('alerts',{id:uid(),deviceId:id,ownerId:d.ownerId,title:'Possible overnight leak',severity:'warning',message:`${d.name} has continuous night flow of ${flowRate.toFixed(1)} L/min.`,resolved:false,createdAt:t})}await renderDevicePanel();renderAll();toast('Reading recorded')};
window.sfMoveDevice=async id=>{const u=currentUser(),hs=(await accounts('households')).filter(h=>h.ownerId===u.id);if(!hs.length)return;const n=Number(prompt('Move device to:\n'+hs.map((h,i)=>`${i+1}. ${h.name}`).join('\n')+'\n\nEnter number:'));const h=hs[n-1],d=(await all('devices')).find(x=>x.id===id);if(!h||!d)return;d.householdId=h.id;await put('devices',d);await renderDevicePanel();toast('Device moved to '+h.name)};
window.sfDeleteDevice=async id=>{const u=currentUser(),d=(await all('devices')).find(x=>x.id===id);if(!u||!d||(u.role!=='admin'&&d.ownerId!==u.id))return;if(!confirm('Delete this device and its readings?'))return;await del('devices',id);for(const r of await all('readings'))if(r.deviceId===id)await del('readings',r.id);for(const a of await all('alerts'))if(a.deviceId===id)await del('alerts',a.id);await renderDevicePanel();toast('Device deleted')};
window.sfDeviceDetail=async id=>{const d=(await all('devices')).find(x=>x.id===id);if(!d)return;const rs=(await all('readings')).filter(x=>x.deviceId===id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,12),as=(await all('alerts')).filter(x=>x.deviceId===id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const latest=rs[0];const body=`<div class="device"><div class="deviceTop"><div><b>📡 ${esc(d.name)}</b><small>${esc(d.type||'Water meter')} · ${esc(d.location||'Household')}</small></div><span class="health ${as.some(a=>!a.resolved&&a.severity==='critical')?'attention':''}">${as.some(a=>!a.resolved&&a.severity==='critical')?'Attention':'Healthy'}</span></div><div class="deviceGrid"><div><small>Latest flow</small><strong>${latest?Number(latest.flow).toFixed(2):'0.00'} L/min</strong></div><div><small>Latest litres</small><strong>${latest?Number(latest.litres).toFixed(1):'—'} L</strong></div><div><small>Readings</small><strong>${rs.length}</strong></div></div></div><h3>Recent readings</h3>${rs.length?rs.map(r=>`<div class="sf-small">${new Date(r.createdAt).toLocaleString()} · ${Number(r.litres).toFixed(1)} L · ${Number(r.flow).toFixed(2)} L/min</div>`).join(''):'<div class="empty">No readings yet.</div>'}<h3>Device alerts</h3>${as.length?as.map(a=>`<div class="sf-small">${a.resolved?'✓ Resolved':'⚠ Active'} · ${esc(a.title)} · ${new Date(a.createdAt).toLocaleString()}</div>`).join(''):'<div class="empty">No device alerts.</div>'}`;simpleModal('Device monitor',body)};
function simpleModal(title,body){let m=$('sfRuntimeModal');if(!m){m=document.createElement('div');m.id='sfRuntimeModal';m.className='sf-modal';document.body.appendChild(m)}m.innerHTML=`<div class="sf-box"><div class="row"><h2 style="margin:0">${title}</h2><button class="btn soft" onclick="document.getElementById('sfRuntimeModal').classList.remove('open')">×</button></div><div style="margin-top:12px">${body}</div></div>`;m.classList.add('open')}
window.sfHouseholdDetail=async id=>{const u=currentUser(),hs=(await accounts('households')).filter(h=>h.ownerId===u.id),h=hs.find(x=>x.id===id),ds=(await all('devices')).filter(d=>d.ownerId===u.id&&d.householdId===id),rs=await all('readings'),as=await all('alerts');if(!h)return;const total=ds.reduce((n,d)=>{const r=rs.filter(x=>x.deviceId===d.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];return n+(r?Number(r.litres):0)},0);simpleModal(`🏠 ${esc(h.name)}`,`<p class="sf-small">${esc(h.address||'Address not set')}</p><div class="deviceGrid"><div><small>Devices</small><strong>${ds.length}</strong></div><div><small>Latest litres</small><strong>${total.toFixed(1)} L</strong></div><div><small>Open alerts</small><strong>${as.filter(a=>ds.some(d=>d.id===a.deviceId)&&!a.resolved).length}</strong></div></div><div class="device-actions"><button class="btn dark" onclick="document.getElementById('sfRuntimeModal').classList.remove('open');sfAddHouseholdDevice()">+ Add device</button></div>${ds.length?ds.map(d=>deviceCard(d,rs,as)).join(''):'<div class="empty">This household has no devices yet.</div>'}`)};
window.sfHouseholdsManager=async()=>{const u=currentUser();if(!u)return window.sfOpenAccount?.();const hs=(await accounts('households')).filter(h=>h.ownerId===u.id);simpleModal('My households',`<div class="device-actions"><button class="btn dark" onclick="sfCreateHousehold()">+ Add household</button></div>${hs.length?hs.map(h=>`<div class="house"><div class="househead"><button class="iconbtn" onclick="sfHouseholdDetail('${h.id}')">🏠 ${esc(h.name)}</button><span>Open details →</span></div><small>${esc(h.address||'Address not set')}</small></div>`).join(''):'<div class="empty">No households yet.</div>'}`)};
window.sfCreateHousehold=async()=>{const u=currentUser();if(!u)return;const name=prompt('Household name','My Home');if(!name?.trim())return;const address=prompt('Address / area','Gaborone')||'';const d=await openAccountsForWrite();await new Promise((ok,bad)=>{const q=d.transaction('households','readwrite').objectStore('households').put({id:uid(),ownerId:u.id,name:name.trim(),address:address.trim(),createdAt:new Date().toISOString()});q.onsuccess=ok;q.onerror=()=>bad(q.error)});await renderDevicePanel();await sfHouseholdsManager();toast('Household created')};
async function openAccountsForWrite(){return new Promise((ok,bad)=>{const r=indexedDB.open('smartflow-accounts-v2',1);r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)})}
function renderChart(m){const c=$('chart');if(!c)return;const mx=Math.max(...m.rs.map(x=>x.flow),.01);c.innerHTML=m.rs.map(x=>`<div class="barc" title="${x.hour}:00 · ${x.flow.toFixed(2)} L/min" style="height:${Math.max(6,x.flow/mx*100)}%"></div>`).join('')}
async function renderAlerts(){const b=$('alertsList');if(!b)return;const m=metrics(),a=[];if(S.scenario==='overnight')a.push(['warning','Possible overnight leak','Continuous night flow is above the normal idle pattern.']);if(S.scenario==='high'&&m.current>5)a.push(['critical','High flow / burst risk',`Current simulated flow is ${m.current.toFixed(1)} L/min.`]);if(S.scenario==='spike'&&S.hour>=18&&S.hour<=21)a.push(['warning','Evening usage spike','The selected hour is inside a simulated evening peak.']);const u=currentUser();if(u){for(const x of (await all('alerts')).filter(x=>x.ownerId===u.id&&!x.resolved).slice(-5).reverse())a.push([x.severity||'warning',x.title,x.message||'Device alert']);}b.innerHTML=a.length?a.map(x=>`<div class="alert ${x[0]==='critical'?'critical':''}"><div><b>${esc(x[1])}</b><small>Live Smart Flow state · ${String(S.hour).padStart(2,'0')}:00</small><p>${esc(x[2])}</p></div><button class="btn soft" onclick="sfAcknowledgeAlert()">Acknowledge</button></div>`).join(''):'<div class="healthy"><div class="pulse">✓</div><b>All clear</b><p>Thothi is actively monitoring the selected scenario and device state.</p></div>'}
window.sfAcknowledgeAlert=async()=>{toast('Alert acknowledged');renderAll()};
function renderAll(){const m=metrics(),name=SC[S.scenario][0];if($('scenario'))$('scenario').value=S.scenario;if($('hour'))$('hour').value=S.hour;if($('timeLabel'))$('timeLabel').textContent=String(S.hour).padStart(2,'0')+':00';if($('scenarioName'))$('scenarioName').textContent=name;if($('scenarioBadge'))$('scenarioBadge').textContent=SC[S.scenario][1];if($('mToday'))$('mToday').textContent=Math.round(m.total)+' L';if($('mBill'))$('mBill').textContent='P'+m.forecast.toFixed(0);if($('mFlow'))$('mFlow').textContent=m.current.toFixed(2)+' L/min';if($('mSave'))$('mSave').textContent='P'+m.saving.toFixed(0);if($('billCurrent'))$('billCurrent').textContent='P'+(m.forecast*.47).toFixed(0);if($('billForecast'))$('billForecast').textContent='P'+m.forecast.toFixed(0);if($('billUsed'))$('billUsed').textContent=Math.round(m.total*.47)+' L used';if($('billExplain'))$('billExplain').textContent=`${name}: the forecast is calculated from the same simulated readings shown on Overview.`;if($('cyclePct'))$('cyclePct').textContent='47%';if($('cycleFill'))$('cycleFill').style.width='47%';if($('insightTitle'))$('insightTitle').textContent=S.scenario==='normal'?'Thothi is watching. 👀':'Thothi spotted a pattern. 💧';if($('insightText'))$('insightText').textContent=S.scenario==='overnight'?'Night flow is elevated. Check toilets, taps and hidden leaks.':S.scenario==='high'?'Flow is unusually high. Check for burst-pipe risk.':S.scenario==='improving'?'Your simulated usage is trending lower. Keep it going!':'Everything is calm in this simulation.';renderChart(m);renderTasks();renderDevicePanel();renderAlerts()}
window.advanceHour=d=>{S.hour=(S.hour+d+24)%24;renderAll();emotion(S.scenario==='normal'?'happy':'concerned');toast(`Simulation time ${String(S.hour).padStart(2,'0')}:00`)};
window.runScenario=()=>{if(S.playing)return;S.playing=true;emotion('excited');toast('Running 24-hour intelligence test…');let i=0;const timer=setInterval(()=>{S.hour=i;renderAll();i++;if(i>23){clearInterval(timer);S.playing=false;emotion('celebrating');toast('24-hour test complete');message('24-hour simulation complete. The chart, forecast, alerts and Thothi all followed the same timeline. 💧')}},160)};
function wire(){const sel=$('scenario');if(sel)sel.onchange=()=>{S.scenario=sel.value;S.hour=Number($('hour')?.value??12);renderAll();emotion(S.scenario==='normal'?'happy':S.scenario==='improving'?'excited':'concerned');message(`I switched to ${SC[S.scenario][0]}. Watch the dashboard and alerts change with me.`)};const hour=$('hour');if(hour)hour.oninput=()=>{S.hour=Number(hour.value);renderAll()};document.querySelectorAll('[data-action="prev"]').forEach(b=>b.onclick=()=>window.advanceHour(-1));document.querySelectorAll('[data-action="next"]').forEach(b=>b.onclick=()=>window.advanceHour(1));document.querySelectorAll('[data-action="run"]').forEach(b=>b.onclick=window.runScenario);const sug=$('suggestions');if(sug)sug.innerHTML=PROMPTS.map(p=>`<button class="prompt" onclick="sfAsk(${JSON.stringify(p)})">${esc(p)}</button>`).join('');window.sfAsk=p=>{const i=$('chatInput');if(i)i.value=p;askThothiInternal(p)};window.askThothi=()=>{const i=$('chatInput'),q=(i?.value||'').trim();if(i)i.value='';askThothiInternal(q)};$('chatInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')window.askThothi()});if($('chat')&&!$('chat').children.length)message('Hi! I’m Thothi 💧 Choose a question below — you do not have to type first.');renderAll();emotion('happy');window.__smartFlowRuntimeReady=true}
function boot(){setTimeout(()=>{try{wire()}catch(e){console.error('Smart Flow runtime boot error',e);toast('Smart Flow recovered a runtime error — reload once if needed.')}const splash=$('splash');setTimeout(()=>splash?.classList.add('hide'),1700)},80)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
