/* Smart Flow BW runtime — demo/offline functionality layer. */
(function(){'use strict';
const DB='smartflow-local-v1',VER=2;
const state={scenario:'normal',hour:12,history:[],lastReply:null};
const q=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{for(const s of ['devices','readings','alerts','tasks','settings'])if(!r.result.objectStoreNames.contains(s))r.result.createObjectStore(s,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function all(store){try{const d=await openDb();return await new Promise((res,rej)=>{if(!d.objectStoreNames.contains(store))return res([]);const x=d.transaction(store,'readonly').objectStore(store).getAll();x.onsuccess=()=>res(x.result||[]);x.onerror=()=>rej(x.error)})}catch{return []}}
async function put(store,obj){const d=await openDb();return new Promise((res,rej)=>{const x=d.transaction(store,'readwrite').objectStore(store).put(obj);x.onsuccess=()=>res(obj);x.onerror=()=>rej(x.error)})}
async function del(store,id){const d=await openDb();return new Promise((res,rej)=>{const x=d.transaction(store,'readwrite').objectStore(store).delete(id);x.onsuccess=()=>res();x.onerror=()=>rej(x.error)})}
function currentUser(){try{return JSON.parse(localStorage.getItem('sf.session')||'null')}catch{return null}}
function toast(t){if(typeof window.showToast==='function'){try{return window.showToast(t)}catch{}}let x=q('sfRuntimeToast');if(!x){x=document.createElement('div');x.id='sfRuntimeToast';x.style='position:fixed;bottom:18px;left:50%;transform:translateX(-50%);z-index:300;background:#08243d;color:#fff;padding:11px 15px;border-radius:12px;font-weight:800;font-size:12px';document.body.appendChild(x)}x.textContent=t;x.style.display='block';clearTimeout(x._t);x._t=setTimeout(()=>x.style.display='none',2200)}
function model(){const s=state.scenario,h=state.hour;let base=42,flow=.55;const hours=Array.from({length:24},(_,i)=>{let v=base/4;if(i>=6&&i<=8)v*=1.7;if(i>=18&&i<=21)v*=2.1;if(s==='overnight'&&i>=22)v*=1.5;if(s==='high'&&i===h)v*=5.2;if(s==='spike'&&i===19)v*=4.3;if(s==='improving')v*=.78;return Math.max(1,v)});if(s==='overnight')flow=.7;if(s==='high')flow=6.8;if(s==='spike')flow=h>=18&&h<=21?4.4:.7;if(s==='improving')flow=.42;return {hours,flow,total:hours.reduce((a,b)=>a+b,0),daily:hours.reduce((a,b)=>a+b,0)}}
function renderChart(m){const c=q('chart');if(!c)return;const mx=Math.max(...m.hours);c.innerHTML=m.hours.map((v,i)=>`<div class="barc" title="${i}:00 · ${v.toFixed(1)} L" style="height:${Math.max(6,v/mx*100)}%"></div>`).join('')}
function billEstimate(l){const bands=[{max:5,rate:1.8},{max:15,rate:3.2},{max:30,rate:5.1},{max:50,rate:7.4},{max:Infinity,rate:9.2}];let rem=l,c=0,prev=0;for(const b of bands){const take=Math.max(0,Math.min(rem,b.max-prev));c+=take*b.rate;rem-=take;if(rem<=0)break;prev=b.max}return c}
function renderAll(){state.scenario=q('scenario')?.value||state.scenario;state.hour=Number(q('hour')?.value||state.hour);if(q('timeLabel'))q('timeLabel').textContent=String(state.hour).padStart(2,'0')+':00';const m=model(),daily=m.total;const current=billEstimate(daily*.45),forecast=billEstimate(daily*30);if(q('mToday'))q('mToday').textContent=Math.round(daily)+' L';if(q('mBill'))q('mBill').textContent='P'+forecast.toFixed(0);if(q('mFlow'))q('mFlow').textContent=m.flow.toFixed(1)+' L/min';if(q('mSave'))q('mSave').textContent='P'+Math.max(0,forecast*.12).toFixed(0);if(q('billCurrent'))q('billCurrent').textContent='P'+current.toFixed(0);if(q('billForecast'))q('billForecast').textContent='P'+forecast.toFixed(0);if(q('billUsed'))q('billUsed').textContent=Math.round(daily*.45)+' L used';if(q('billDays'))q('billDays').textContent='14 days elapsed';if(q('cyclePct'))q('cyclePct').textContent='47%';if(q('cycleFill'))q('cycleFill').style.width='47%';const labels={normal:'Normal',overnight:'Possible leak',high:'Burst risk',improving:'Improving',spike:'Evening spike'};if(q('scenarioBadge')){q('scenarioBadge').textContent=labels[state.scenario];q('scenarioBadge').className='delta '+(state.scenario==='normal'||state.scenario==='improving'?'good':'warn')}if(q('insightTitle'))q('insightTitle').textContent=state.scenario==='normal'?'Thothi is watching. 👀':'Thothi spotted a pattern. 💧';if(q('insightText'))q('insightText').textContent=state.scenario==='overnight'?'Low flow through the night can mean a running toilet, tap or hidden leak.':state.scenario==='high'?'That flow is unusually high. Check for open taps and burst-pipe risk.':state.scenario==='improving'?'Nice. The simulated pattern is trending lower than the baseline.':'Everything is being simulated from the selected household scenario.';if(q('billExplain'))q('billExplain').textContent=`Scenario: ${labels[state.scenario]}. Forecast is a Smart Flow simulation, not an official WUC bill.`;renderChart(m);renderAlerts();renderTasks();renderDevices()}
window.renderAll=renderAll;window.advanceHour=d=>{const h=(state.hour+d+24)%24;if(q('hour'))q('hour').value=h;renderAll()};window.runScenario=()=>{let i=0;toast('Running 24-hour intelligence test…');const timer=setInterval(()=>{state.hour=i;if(q('hour'))q('hour').value=i;renderAll();i++;if(i>23){clearInterval(timer);toast('24-hour test complete')}},90)};
function renderAlerts(){const box=q('alertsList');if(!box)return;const m=model(),alerts=[];if(state.scenario==='overnight')alerts.push({severity:'warning',title:'Possible overnight leak',desc:'Simulated low continuous night flow is above the normal idle range.'});if(state.scenario==='high')alerts.push({severity:'critical',title:'High flow detected',desc:`Simulated flow reached ${m.flow.toFixed(1)} L/min.`});if(state.scenario==='spike')alerts.push({severity:'warning',title:'Evening spike',desc:'A simulated usage spike appears in the evening window.'});box.innerHTML=alerts.length?alerts.map(a=>`<div class="alert ${a.severity==='critical'?'critical':''}"><b>${a.title}</b><p>${a.desc}</p><button class="btn dark" onclick="this.parentElement.remove();toast('Alert acknowledged')">Acknowledge</button></div>`).join(''):'<div class="card empty">No active alerts. Thothi is not seeing anything unusual in the selected simulation.</div>'}
async function renderTasks(){const box=q('tasks');if(!box)return;const ts=await all('tasks'),u=currentUser(),list=ts.filter(t=>!u||t.ownerId===u.id||u.role==='admin');box.innerHTML=list.length?list.map(t=>`<div class="task"><input type="checkbox" ${t.done?'checked':''} onchange="sfTaskToggle('${t.id}',this.checked)"><span style="flex:1;text-decoration:${t.done?'line-through':'none'};opacity:${t.done?.55:1}">${esc(t.text)}${t.cancelled?' · Cancelled':''}</span><button class="btn soft" onclick="sfTaskCancel('${t.id}')">${t.cancelled?'Cancelled':'Cancel'}</button></div>`).join(''):'<div class="empty">No saving actions yet. Add one and Thothi will help you track it.</div>'}
async function saveTask(text){const u=currentUser()||{id:'demo-user'};await put('tasks',{id:crypto.randomUUID(),ownerId:u.id,text:text.trim(),done:false,cancelled:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});await renderTasks()}
window.addTask=async()=>{const t=prompt('What water-saving action should we add?');if(t&&t.trim()){await saveTask(t);toast('Water-saving action added')}};window.sfTaskToggle=async(id,v)=>{const ts=await all('tasks'),t=ts.find(x=>x.id===id);if(t){t.done=v;t.cancelled=false;t.updatedAt=new Date().toISOString();await put('tasks',t);await renderTasks();toast(v?'Task completed':'Task reopened')}};window.sfTaskCancel=async id=>{const ts=await all('tasks'),t=ts.find(x=>x.id===id);if(t){t.cancelled=true;t.updatedAt=new Date().toISOString();await put('tasks',t);await renderTasks();toast('Task cancelled')}};
function emotion(kind){const c=q('thothiChar');if(!c)return;c.dataset.emotion=kind;c.style.transform=kind==='concerned'?'translateY(-4px) scale(1.04)':kind==='excited'?'translateY(-10px) scale(1.08)':kind==='happy'?'translateY(-7px) scale(1.03)':'';clearTimeout(c._e);c._e=setTimeout(()=>{c.style.transform=''},900)}
function addMsg(text,who){const box=q('chat');if(!box)return;const d=document.createElement('div');d.className='msg '+(who==='user'?'user':'thothi');d.textContent=text;box.appendChild(d);box.scrollTop=box.scrollHeight}
function answer(question){const qn=question.toLowerCase().trim();const m=model();let content='',mood='happy';if(/^(hi|hello|hey|dumela|good morning|good day)[!. ]*$/i.test(question.trim()))content='Hello 👋 I am Thothi. Ask me about your water usage, bill forecast, leaks, alerts or ways to save water.';else if(qn.includes('leak')||qn.includes('drip')||qn.includes('overnight')){mood='concerned';content=state.scenario==='overnight'?`I’ve spotted something. The selected simulation has low continuous night flow, which can point to a running toilet, tap or hidden leak.`:'I do not see a leak signature in the current simulation. Switch to Overnight leak and I can show you what I would flag.'}else if(qn.includes('bill')||qn.includes('cost')||qn.includes('pula')||qn.includes('tariff'))content=`The current simulation forecasts about P${billEstimate(m.total*30).toFixed(0)} for a 30-day pattern. That is a Smart Flow estimate, not an official WUC bill.`;else if(qn.includes('today')||qn.includes('usage')||qn.includes('litre')||qn.includes('water'))content=`The selected scenario is using about ${Math.round(m.total)} litres in this simulated day, with ${m.flow.toFixed(1)} L/min at the selected time. These are test readings, not a live meter.`;else if(qn.includes('save')||qn.includes('reduce')||qn.includes('tip')||qn.includes('advice')){mood='excited';content='Start with the biggest avoidable flow: fix leaks, shorten showers, and avoid running taps while doing other tasks. Add a saving action below and I can track it with your simulated readings.'}else if(qn.includes('alert')||qn.includes('warning')){mood=state.scenario==='normal'?'happy':'concerned';content=state.scenario==='normal'?'No active simulated warning right now.':'There is a simulated warning. Open Alerts to inspect it.'}else content='I can help with usage, leaks, alerts, bill estimates and saving water. Try “How much water am I using?”, “Do I have a leak?”, or “How can I save water?”';return {content,mood}}
window.askThothi=async()=>{const input=q('chatInput'),question=(input?.value||'').trim();if(!question)return;addMsg(question,'user');input.value='';emotion('thinking');const typing=document.createElement('div');typing.id='thothiTyping';typing.className='msg thothi';typing.textContent='Thothi is thinking…';q('chat')?.appendChild(typing);setTimeout(()=>{typing.remove();const a=answer(question);addMsg(a.content,'thothi');emotion(a.mood)},350)};
function setupThothi(){const sug=q('suggestions');if(sug){const prompts=['How much am I using?','Do I have a leak?','What will my bill be?','How can I save water?'];sug.innerHTML=prompts.map(p=>`<button class="btn soft" onclick="sfAsk('${p.replace(/'/g,"\\'")}')">${p}</button>`).join('')} }window.sfAsk=p=>{if(q('chatInput')){q('chatInput').value=p;window.askThothi()}};
function installDeviceUI(){const nav=document.querySelector('.tabs'),main=document.querySelector('main.wrap');if(!nav||!main)return;if(!q('sfDeviceMonitor')){const b=document.createElement('button');b.id='sfDeviceTab';b.className='tab';b.textContent='📡 Device Monitor';b.onclick=()=>openTab('sfDeviceMonitor');nav.appendChild(b);const sec=document.createElement('section');sec.id='sfDeviceMonitor';sec.className='screen';sec.innerHTML='<div class="hero"><h1>Device Monitor</h1><p>Each meter is monitored individually. Record readings, inspect alerts and control device status.</p><button class="btn dark" onclick="sfAddDevice()">+ Add device</button></div><div id="runtimeDevices"></div>';main.appendChild(sec)} }
async function devices(){const u=currentUser(),ds=await all('devices');return u?ds.filter(d=>u.role==='admin'||d.ownerId===u.id):[]}
window.sfAddDevice=async()=>{const u=currentUser();if(!u){return window.sfOpenAccount?.()}const name=prompt('Device name');if(!name?.trim())return;const location=prompt('Location','Main house');await put('devices',{id:crypto.randomUUID(),ownerId:u.id,name:name.trim(),location:(location||'').trim(),type:'Water Meter',status:'online',createdAt:new Date().toISOString(),lastSeen:new Date().toISOString()});await renderDevices();toast('Device added')};
window.sfRecordReading=async id=>{const ds=await all('devices'),d=ds.find(x=>x.id===id),u=currentUser();if(!d||!u||(u.role!=='admin'&&d.ownerId!==u.id))return;const litres=Number(prompt('Litres used','42.5'));const flow=Number(prompt('Flow rate (L/min)','0.7'));if(!Number.isFinite(litres)||!Number.isFinite(flow))return;await put('readings',{id:crypto.randomUUID(),deviceId:id,ownerId:d.ownerId,litres,flow,createdAt:new Date().toISOString(),source:'manual/demo'});d.lastSeen=new Date().toISOString();d.status='online';await put('devices',d);if(flow>5)await put('alerts',{id:crypto.randomUUID(),deviceId:id,ownerId:d.ownerId,title:'High flow detected',severity:'critical',message:`${d.name} is flowing at ${flow.toFixed(1)} L/min.`,resolved:false,createdAt:new Date().toISOString()});await renderDevices();toast('Reading recorded')};
window.sfDeleteDevice=async id=>{const u=currentUser(),ds=await all('devices'),d=ds.find(x=>x.id===id);if(!d||!u||(u.role!=='admin'&&d.ownerId!==u.id))return;if(!confirm('Delete this device and its readings?'))return;await del('devices',id);for(const r of await all('readings'))if(r.deviceId===id)await del('readings',r.id);await renderDevices();toast('Device removed')};
async function renderDevices(){const box=q('runtimeDevices');if(!box)return;const u=currentUser();if(!u){box.innerHTML='<div class="card empty">Sign in to manage your individual devices.</div>';return}const ds=await devices(),rs=await all('readings'),as=await all('alerts');box.innerHTML=ds.length?ds.map(d=>{const r=rs.filter(x=>x.deviceId===d.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0],aa=as.filter(x=>x.deviceId===d.id&&!x.resolved);return `<article class="card" style="margin-bottom:10px"><div class="row"><b>📡 ${esc(d.name)}</b><span class="delta ${d.status==='online'?'good':'warn'}">● ${d.status}</span></div><div class="note">${esc(d.location)} · ${esc(d.type)}</div><div style="font-size:24px;font-weight:850;margin-top:10px">${r?Number(r.flow).toFixed(2):'0.00'} <span style="font-size:12px;color:var(--muted)">L/min</span></div><div class="note">${r?'Last reading '+new Date(r.createdAt).toLocaleString():'No readings yet'} · ${aa.length} active alert${aa.length===1?'':'s'}</div><div class="actions"><button class="btn dark" onclick="sfRecordReading('${d.id}')">＋ Record reading</button><button class="btn soft" onclick="sfDeleteDevice('${d.id}')">Delete</button></div></article>`}).join(''):'<div class="card empty">No devices yet. Add your first water meter.</div>'}
function renderDevicesAfterAuth(){installDeviceUI();renderDevices()}
function boot(){installDeviceUI();setupThothi();renderAll();addMsg('Hi. I’m Thothi 💧 Ask me anything about this simulation.','thothi');renderDevicesAfterAuth()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,300),{once:true});else setTimeout(boot,300);
})();
