import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { mkdirSync, rmSync, cpSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
const root=process.cwd(),site=join(root,'.e2e-site'); rmSync(site,{recursive:true,force:true}); mkdirSync(site,{recursive:true});
for(const f of ['index.html','app.js','local-core.js','auth-admin.js','smartflow-runtime.js','upgrade.js','local-auth-compat.js','manifest.webmanifest','icon.svg']) cpSync(f,join(site,f));
let html=readFileSync(join(site,'index.html'),'utf8'); if(!html.includes('./upgrade.js')) html=html.replace('</body>','<script src="./upgrade.js"></script></body>'); if(!html.includes('./local-auth-compat.js')) html=html.replace('</body>','<script src="./local-auth-compat.js"></script></body>'); writeFileSync(join(site,'index.html'),html);
const server=spawn('python3',['-m','http.server','4173'],{cwd:site,stdio:'ignore'}); const wait=ms=>new Promise(r=>setTimeout(r,ms)); const fail=msg=>{throw new Error(msg)};
try{
 await wait(700); const browser=await chromium.launch({headless:true}); const page=await browser.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(`pageerror: ${e.message}`)); page.on('console',m=>{if(m.type()==='error')errors.push(`console: ${m.text()}`)); page.on('dialog',d=>d.dismiss());
 await page.goto('http://127.0.0.1:4173/index.html',{waitUntil:'domcontentloaded'}); await wait(1800);
 if(await page.locator('.tab').count()<7)fail('Navigation/account tabs did not initialize'); if(!(await page.locator('body').innerText()).includes('Smart Flow BW'))fail('Smart Flow branding did not initialize'); if(await page.locator('img[src="./icon.svg"]').count()<1)fail('Smart Flow brand logo did not initialize');
 const hour=page.locator('#hour'); if(await hour.count()===0)fail('Simulation hour control is missing'); const h0=await hour.innerText(); await page.locator('button:has-text("Next →")').click(); await wait(120); if(await hour.innerText()===h0)fail('Next simulation time button did not move time'); await page.locator('button:has-text("← Previous")').click(); await wait(120); if(await hour.innerText()!==h0)fail('Previous simulation time button did not restore time');
 await page.locator('#scenario').selectOption('high'); await wait(220); if(!(await page.locator('#alertsList').innerText()).includes('High flow / burst risk'))fail('Scenario did not update Alerts'); await page.locator('[data-tab="thothi"]').click(); await wait(180); if(!(await page.locator('#chat').innerText()).includes('Thothi report'))fail('Thothi did not receive current scenario report');
 await page.locator('[data-tab="overview"]').click(); await wait(120); await page.locator('#runBtn').click(); await wait(17500); if(await hour.innerText()!=='23:00')fail('24-hour test did not complete at 23:00');
 await page.locator('[data-tab="thothi"]').click(); await wait(120); const q=page.locator('#prompts .prompt,#prompts button,#suggestions .prompt,#suggestions button').filter({hasText:'What am I looking at?'}).first(); if(await q.count()===0)fail('Guided Thothi question is not clickable'); await q.click(); await wait(250); if(!(await page.locator('#chat').innerText()).includes('Smart Flow command view'))fail('Guided question did not produce an answer');
 await page.locator('#sfAccountBtn').click(); await wait(150); await page.locator('button:has-text("Sign in")').first().click(); await wait(100); if(await page.locator('input[name="email"]').count()===0)fail('Sign-in form did not open'); await page.locator('input[name="email"]').fill('demo@smartflow.local'); await page.locator('input[name="password"]').fill('demo1234'); await page.locator('.sf-box button:has-text("Sign in")').click(); await wait(500); if((await page.evaluate(()=>JSON.parse(localStorage.getItem('sf.session')||'null')))?.email!=='demo@smartflow.local')fail('Demo user sign-in failed');
 await page.locator('[data-tab="devices"]').first().click(); await wait(300); let addDevice=page.locator('#sfDevicePanel button:has-text("Add device")').first(); if(await addDevice.count()===0){const manage=page.locator('#sfDevicePanel button:has-text("Manage households")').first(); if(await manage.count())await manage.click(); await wait(100); const addHouse=page.locator('button:has-text("Add household")').last(); if(await addHouse.count()){await addHouse.click();await wait(100);await page.locator('input[name="name"]').fill('E2E Home');await page.locator('input[name="address"]').fill('Gaborone');await page.locator('.sf-box button:has-text("Create household")').click();await wait(250)} addDevice=page.locator('#sfDevicePanel button:has-text("Add device")').first();}
 if(await addDevice.count()===0)fail('Add device control did not initialize'); await addDevice.click(); await wait(120); const form=page.locator('#sfRuntimeModal form').filter({hasText:'Device name'}); if(await form.count()===0)fail('Add device did not open its form'); await form.locator('input[name="name"]').fill('E2E kitchen meter'); await form.locator('input[name="location"]').fill('Kitchen'); await form.locator('button:has-text("Add device")').click(); await wait(250); if(!(await page.locator('#sfDevicePanel').innerText()).includes('E2E kitchen meter'))fail('Add device save failed');
 await page.locator('[data-tab="save"]').click(); await page.getByRole('button',{name:/Add Action/}).click(); await wait(150); if(!await page.locator('#sfRuntimeModal').count())fail('Add Action did not create runtime modal'); await page.locator('input[name="text"]').fill('E2E test saving action'); await page.locator('#sfRuntimeModal .sf-box button:has-text("Add action")').click(); await wait(180); if(!(await page.locator('#tasks').innerText()).includes('E2E test saving action'))fail('Add Action failed');
 if(errors.length)fail(errors.join('\n')); console.log('Smart Flow BW E2E smoke test: PASS'); console.log('Logo, navigation, simulation, Thothi report/questions, sign-in, Add Device and Save Water CRUD passed.'); await browser.close();
} finally {server.kill('SIGTERM');rmSync(site,{recursive:true,force:true});}
